<div class="container">
	<form method='POST' action="/magento/blog/index/save">
	    <div class="form-group">
	        <label for="name">Name</label>
	        <input type="text" class="form-control" id="name" placeholder="Enter a name" name="name">
	    </div>

	    <div class="form-group">
	    	<label for="address">Address</label>
	        <input type="text" class="form-control" id="address" placeholder="Enter address" name="address">
	    </div>
	    <div class="form-group">
	        <label for="country">Country</label>
	        <input type="text" class="form-control" id="country" placeholder="Enter country" name="country">
	    </div>
	    <div class="form-group">
	        <label for="introduce">Introduce</label>
	        <input type="text" class="form-control" id="introduce" placeholder="Enter introduce" name="introduce">
	    </div>
	    <button type="submit" class="btn btn-primary" name="createbtn">Submit</button>
	</form>
</div>