
<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
         <a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" class="action primary">Create New Post</a>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Country</th>
            <th>Introduce</th>
            <th>Creared At</th>
            <th>Updated At</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody>
    <?php
    $posts = $block->getPosts();

    foreach ($posts as $post) :
        ?>
        <tr style="border: 1px solid #000000; text-align: left; padding: 8px;">
            <td><?php echo $post->getId(); ?></td>
            <td><?php echo $post->getName(); ?></td>
            <td><?php echo $post->getAddress(); ?></td>
            <td><?php echo $post->getCountry(); ?></td>
            <td><?php echo $post->getIntroduce(); ?></td>
            <td><?php echo $post->getCreatedAt(); ?></td>
            <td><?php echo $post->getUpdatedAt(); ?></td>
        ?>      
            <td>
                <a href="/magento/blog/index/edit/post_id/<?= $post->getId() ?>">Edit</a>
            </td>;
            <td>
                <a href="/magento/blog/index/delete/post_id/<?= $post->getId() ?>">Delete</a>
            </td>";
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>